# NB1A - Pokemon Data Collection
This notebook will include the code utilised to collect the data from the PokeAPI. This is the link to the PokeAPI [documentation](https://pokeapi.co/docs/v2). It is of note, however, that some of the doucmentation is outdated and not accurate. These will be highlighted when encountered.

In [12]:
import os
import json
import requests
import pandas as pd

In [13]:
request_url = 'https://pokeapi.co/api/v2/generation/1'
response = requests.get(request_url)
data = response.json()
with open ('../../data/Pokemon Data/generation_1_details.json', 'w') as file: 
    json.dump(data,file)

gen_1_poke_df = pd.json_normalize(data, record_path = 'pokemon_species')
display(gen_1_poke_df)

           name                                             url
0     bulbasaur    https://pokeapi.co/api/v2/pokemon-species/1/
1    charmander    https://pokeapi.co/api/v2/pokemon-species/4/
2      squirtle    https://pokeapi.co/api/v2/pokemon-species/7/
3      caterpie   https://pokeapi.co/api/v2/pokemon-species/10/
4        weedle   https://pokeapi.co/api/v2/pokemon-species/13/
..          ...                                             ...
146   dragonair  https://pokeapi.co/api/v2/pokemon-species/148/
147   dragonite  https://pokeapi.co/api/v2/pokemon-species/149/
148         mew  https://pokeapi.co/api/v2/pokemon-species/151/
149     ivysaur    https://pokeapi.co/api/v2/pokemon-species/2/
150       golem   https://pokeapi.co/api/v2/pokemon-species/76/

[151 rows x 2 columns]

In [14]:
def extract_pokemon_id(url): 
    id = url.rstrip('/').split('/')[-1]
    return int(id)

In [15]:
gen_1_poke_df['pokemon_id'] = gen_1_poke_df['url'].apply(extract_pokemon_id)
display(gen_1_poke_df)
gen_1_poke_df = gen_1_poke_df.sort_values('pokemon_id').reset_index(drop = True)

gen_1_poke_df.to_json('../../data/Pokemon Data/generation_1_pokemon.json')

           name                                             url  pokemon_id
0     bulbasaur    https://pokeapi.co/api/v2/pokemon-species/1/           1
1    charmander    https://pokeapi.co/api/v2/pokemon-species/4/           4
2      squirtle    https://pokeapi.co/api/v2/pokemon-species/7/           7
3      caterpie   https://pokeapi.co/api/v2/pokemon-species/10/          10
4        weedle   https://pokeapi.co/api/v2/pokemon-species/13/          13
..          ...                                             ...         ...
146   dragonair  https://pokeapi.co/api/v2/pokemon-species/148/         148
147   dragonite  https://pokeapi.co/api/v2/pokemon-species/149/         149
148         mew  https://pokeapi.co/api/v2/pokemon-species/151/         151
149     ivysaur    https://pokeapi.co/api/v2/pokemon-species/2/           2
150       golem   https://pokeapi.co/api/v2/pokemon-species/76/          76

[151 rows x 3 columns]

In [16]:
def get_pokemon_details(pokemon_id): 
    request_url = f'https://pokeapi.co/api/v2/pokemon/{pokemon_id}'
    response = requests.get(request_url)
    if response.status_code != 200:
        print(f"Error: Received status code {response.status_code}")
        print(f"Response content: {response.text}")
    else:
        data = response.json()
        with open(f'../../data/Pokemon Data/generation_1_pokemon_details/pokemon_{pokemon_id}_details', 'w') as file:
            json.dump(data, file)
        print(f"Data successfully obtained for Pokemon with ID {pokemon_id}.")
    return 

get_pokemon_details(1)

Data successfully obtained for Pokemon with ID 1.

In [17]:
def get_pokemon_species_details(pokemon_id): 
    request_url = f'https://pokeapi.co/api/v2/pokemon-species/{pokemon_id}'
    response = requests.get(request_url)
    if response.status_code != 200:
        print(f"Error: Received status code {response.status_code}")
        print(f"Response content: {response.text}")
    else:
        data = response.json()
        with open(f'../../data/Pokemon Data/generation_1_species_details/pokemon_{pokemon_id}_species_details', 'w') as file:
            json.dump(data, file)
        print(f"Data successfully obtained for Pokemon with ID {pokemon_id}.")
    return 

get_pokemon_species_details(1)

Data successfully obtained for Pokemon with ID 1.

In [18]:
def main(pokemon_id):
    get_pokemon_details(pokemon_id)
    get_pokemon_species_details(pokemon_id)
    
gen_1_poke_df['pokemon_id'].apply(main)

Data successfully obtained for Pokemon with ID 1.
Data successfully obtained for Pokemon with ID 1.
Data successfully obtained for Pokemon with ID 2.
Data successfully obtained for Pokemon with ID 2.
Data successfully obtained for Pokemon with ID 3.
Data successfully obtained for Pokemon with ID 3.
Data successfully obtained for Pokemon with ID 4.
Data successfully obtained for Pokemon with ID 4.
Data successfully obtained for Pokemon with ID 5.
Data successfully obtained for Pokemon with ID 5.
Data successfully obtained for Pokemon with ID 6.
Data successfully obtained for Pokemon with ID 6.
Data successfully obtained for Pokemon with ID 7.
Data successfully obtained for Pokemon with ID 7.
Data successfully obtained for Pokemon with ID 8.
Data successfully obtained for Pokemon with ID 8.
Data successfully obtained for Pokemon with ID 9.
Data successfully obtained for Pokemon with ID 9.
Data successfully obtained for Pokemon with ID 10.
Data successfully obtained for Pokemon with ID 10.
Data successfully obtained for Pokemon with ID 11.
Data successfully obtained for Pokemon with ID 11.
Data successfully obtained for Pokemon with ID 12.
Data successfully obtained for Pokemon with ID 12.
Data successfully obtained for Pokemon with ID 13.
Data successfully obtained for Pokemon with ID 13.
Data successfully obtained for Pokemon with ID 14.
Data successfully obtained for Pokemon with ID 14.
Data successfully obtained for Pokemon with ID 15.
Data successfully obtained for Pokemon with ID 15.
Data successfully obtained for Pokemon with ID 16.
Data successfully obtained for Pokemon with ID 16.
Data successfully obtained for Pokemon with ID 17.
Data successfully obtained for Pokemon with ID 17.
Data successfully obtained for Pokemon with ID 18.
Data successfully obtained for Pokemon with ID 18.
Data successfully obtained for Pokemon with ID 19.
Data successfully obtained for Pokemon with ID 19.
Data successfully obtained for Pokemon with ID 20.
Data successfully obtained for Pokemon with ID 20.
Data successfully obtained for Pokemon with ID 21.
Data successfully obtained for Pokemon with ID 21.
Data successfully obtained for Pokemon with ID 22.
Data successfully obtained for Pokemon with ID 22.
Data successfully obtained for Pokemon with ID 23.
Data successfully obtained for Pokemon with ID 23.
Data successfully obtained for Pokemon with ID 24.
Data successfully obtained for Pokemon with ID 24.
Data successfully obtained for Pokemon with ID 25.
Data successfully obtained for Pokemon with ID 25.
Data successfully obtained for Pokemon with ID 26.
Data successfully obtained for Pokemon with ID 26.
Data successfully obtained for Pokemon with ID 27.
Data successfully obtained for Pokemon with ID 27.
Data successfully obtained for Pokemon with ID 28.
Data successfully obtained for Pokemon with ID 28.
Data successfully obtained for Pokemon with ID 29.
Data successfully obtained for Pokemon with ID 29.
Data successfully obtained for Pokemon with ID 30.
Data successfully obtained for Pokemon with ID 30.
Data successfully obtained for Pokemon with ID 31.
Data successfully obtained for Pokemon with ID 31.
Data successfully obtained for Pokemon with ID 32.
Data successfully obtained for Pokemon with ID 32.
Data successfully obtained for Pokemon with ID 33.
Data successfully obtained for Pokemon with ID 33.
Data successfully obtained for Pokemon with ID 34.
Data successfully obtained for Pokemon with ID 34.
Data successfully obtained for Pokemon with ID 35.
Data successfully obtained for Pokemon with ID 35.
Data successfully obtained for Pokemon with ID 36.
Data successfully obtained for Pokemon with ID 36.
Data successfully obtained for Pokemon with ID 37.
Data successfully obtained for Pokemon with ID 37.
Data successfully obtained for Pokemon with ID 38.
Data successfully obtained for Pokemon with ID 38.
Data successfully obtained for Pokemon with ID 39.
Data successfully obtained for Pokemon with ID 39.
Data successfully obtained for Pokemon with ID 40.
Data successfully obtained for Pokemon with ID 40.
Data successfully obtained for Pokemon with ID 41.
Data successfully obtained for Pokemon with ID 41.
Data successfully obtained for Pokemon with ID 42.
Data successfully obtained for Pokemon with ID 42.
Data successfully obtained for Pokemon with ID 43.
Data successfully obtained for Pokemon with ID 43.
Data successfully obtained for Pokemon with ID 44.
Data successfully obtained for Pokemon with ID 44.
Data successfully obtained for Pokemon with ID 45.
Data successfully obtained for Pokemon with ID 45.
Data successfully obtained for Pokemon with ID 46.
Data successfully obtained for Pokemon with ID 46.
Data successfully obtained for Pokemon with ID 47.
Data successfully obtained for Pokemon with ID 47.
Data successfully obtained for Pokemon with ID 48.
Data successfully obtained for Pokemon with ID 48.
Data successfully obtained for Pokemon with ID 49.
Data successfully obtained for Pokemon with ID 49.
Data successfully obtained for Pokemon with ID 50.
Data successfully obtained for Pokemon with ID 50.
Data successfully obtained for Pokemon with ID 51.
Data successfully obtained for Pokemon with ID 51.
Data successfully obtained for Pokemon with ID 52.
Data successfully obtained for Pokemon with ID 52.
Data successfully obtained for Pokemon with ID 53.
Data successfully obtained for Pokemon with ID 53.
Data successfully obtained for Pokemon with ID 54.
Data successfully obtained for Pokemon with ID 54.
Data successfully obtained for Pokemon with ID 55.
Data successfully obtained for Pokemon with ID 55.
Data successfully obtained for Pokemon with ID 56.
Data successfully obtained for Pokemon with ID 56.
Data successfully obtained for Pokemon with ID 57.
Data successfully obtained for Pokemon with ID 57.
Data successfully obtained for Pokemon with ID 58.
Data successfully obtained for Pokemon with ID 58.
Data successfully obtained for Pokemon with ID 59.
Data successfully obtained for Pokemon with ID 59.
Data successfully obtained for Pokemon with ID 60.
Data successfully obtained for Pokemon with ID 60.
Data successfully obtained for Pokemon with ID 61.
Data successfully obtained for Pokemon with ID 61.
Data successfully obtained for Pokemon with ID 62.
Data successfully obtained for Pokemon with ID 62.
Data successfully obtained for Pokemon with ID 63.
Data successfully obtained for Pokemon with ID 63.
Data successfully obtained for Pokemon with ID 64.
Data successfully obtained for Pokemon with ID 64.
Data successfully obtained for Pokemon with ID 65.
Data successfully obtained for Pokemon with ID 65.
Data successfully obtained for Pokemon with ID 66.
Data successfully obtained for Pokemon with ID 66.
Data successfully obtained for Pokemon with ID 67.
Data successfully obtained for Pokemon with ID 67.
Data successfully obtained for Pokemon with ID 68.
Data successfully obtained for Pokemon with ID 68.
Data successfully obtained for Pokemon with ID 69.
Data successfully obtained for Pokemon with ID 69.
Data successfully obtained for Pokemon with ID 70.
Data successfully obtained for Pokemon with ID 70.
Data successfully obtained for Pokemon with ID 71.
Data successfully obtained for Pokemon with ID 71.
Data successfully obtained for Pokemon with ID 72.
Data successfully obtained for Pokemon with ID 72.
Data successfully obtained for Pokemon with ID 73.
Data successfully obtained for Pokemon with ID 73.
Data successfully obtained for Pokemon with ID 74.
Data successfully obtained for Pokemon with ID 74.
Data successfully obtained for Pokemon with ID 75.
Data successfully obtained for Pokemon with ID 75.
Data successfully obtained for Pokemon with ID 76.
Data successfully obtained for Pokemon with ID 76.
Data successfully obtained for Pokemon with ID 77.
Data successfully obtained for Pokemon with ID 77.
Data successfully obtained for Pokemon with ID 78.
Data successfully obtained for Pokemon with ID 78.
Data successfully obtained for Pokemon with ID 79.
Data successfully obtained for Pokemon with ID 79.
Data successfully obtained for Pokemon with ID 80.
Data successfully obtained for Pokemon with ID 80.
Data successfully obtained for Pokemon with ID 81.
Data successfully obtained for Pokemon with ID 81.
Data successfully obtained for Pokemon with ID 82.
Data successfully obtained for Pokemon with ID 82.
Data successfully obtained for Pokemon with ID 83.
Data successfully obtained for Pokemon with ID 83.
Data successfully obtained for Pokemon with ID 84.
Data successfully obtained for Pokemon with ID 84.
Data successfully obtained for Pokemon with ID 85.
Data successfully obtained for Pokemon with ID 85.
Data successfully obtained for Pokemon with ID 86.
Data successfully obtained for Pokemon with ID 86.
Data successfully obtained for Pokemon with ID 87.
Data successfully obtained for Pokemon with ID 87.
Data successfully obtained for Pokemon with ID 88.
Data successfully obtained for Pokemon with ID 88.
Data successfully obtained for Pokemon with ID 89.
Data successfully obtained for Pokemon with ID 89.
Data successfully obtained for Pokemon with ID 90.
Data successfully obtained for Pokemon with ID 90.
Data successfully obtained for Pokemon with ID 91.
Data successfully obtained for Pokemon with ID 91.
Data successfully obtained for Pokemon with ID 92.
Data successfully obtained for Pokemon with ID 92.
Data successfully obtained for Pokemon with ID 93.
Data successfully obtained for Pokemon with ID 93.
Data successfully obtained for Pokemon with ID 94.
Data successfully obtained for Pokemon with ID 94.
Data successfully obtained for Pokemon with ID 95.
Data successfully obtained for Pokemon with ID 95.
Data successfully obtained for Pokemon with ID 96.
Data successfully obtained for Pokemon with ID 96.
Data successfully obtained for Pokemon with ID 97.
Data successfully obtained for Pokemon with ID 97.
Data successfully obtained for Pokemon with ID 98.
Data successfully obtained for Pokemon with ID 98.
Data successfully obtained for Pokemon with ID 99.
Data successfully obtained for Pokemon with ID 99.
Data successfully obtained for Pokemon with ID 100.
Data successfully obtained for Pokemon with ID 100.
Data successfully obtained for Pokemon with ID 101.
Data successfully obtained for Pokemon with ID 101.
Data successfully obtained for Pokemon with ID 102.
Data successfully obtained for Pokemon with ID 102.
Data successfully obtained for Pokemon with ID 103.
Data successfully obtained for Pokemon with ID 103.
Data successfully obtained for Pokemon with ID 104.
Data successfully obtained for Pokemon with ID 104.
Data successfully obtained for Pokemon with ID 105.
Data successfully obtained for Pokemon with ID 105.
Data successfully obtained for Pokemon with ID 106.
Data successfully obtained for Pokemon with ID 106.
Data successfully obtained for Pokemon with ID 107.
Data successfully obtained for Pokemon with ID 107.
Data successfully obtained for Pokemon with ID 108.
Data successfully obtained for Pokemon with ID 108.
Data successfully obtained for Pokemon with ID 109.
Data successfully obtained for Pokemon with ID 109.
Data successfully obtained for Pokemon with ID 110.
Data successfully obtained for Pokemon with ID 110.
Data successfully obtained for Pokemon with ID 111.
Data successfully obtained for Pokemon with ID 111.
Data successfully obtained for Pokemon with ID 112.
Data successfully obtained for Pokemon with ID 112.
Data successfully obtained for Pokemon with ID 113.
Data successfully obtained for Pokemon with ID 113.
Data successfully obtained for Pokemon with ID 114.
Data successfully obtained for Pokemon with ID 114.
Data successfully obtained for Pokemon with ID 115.
Data successfully obtained for Pokemon with ID 115.
Data successfully obtained for Pokemon with ID 116.
Data successfully obtained for Pokemon with ID 116.
Data successfully obtained for Pokemon with ID 117.
Data successfully obtained for Pokemon with ID 117.
Data successfully obtained for Pokemon with ID 118.
Data successfully obtained for Pokemon with ID 118.
Data successfully obtained for Pokemon with ID 119.
Data successfully obtained for Pokemon with ID 119.
Data successfully obtained for Pokemon with ID 120.
Data successfully obtained for Pokemon with ID 120.
Data successfully obtained for Pokemon with ID 121.
Data successfully obtained for Pokemon with ID 121.
Data successfully obtained for Pokemon with ID 122.
Data successfully obtained for Pokemon with ID 122.
Data successfully obtained for Pokemon with ID 123.
Data successfully obtained for Pokemon with ID 123.
Data successfully obtained for Pokemon with ID 124.
Data successfully obtained for Pokemon with ID 124.
Data successfully obtained for Pokemon with ID 125.
Data successfully obtained for Pokemon with ID 125.
Data successfully obtained for Pokemon with ID 126.
Data successfully obtained for Pokemon with ID 126.
Data successfully obtained for Pokemon with ID 127.
Data successfully obtained for Pokemon with ID 127.
Data successfully obtained for Pokemon with ID 128.
Data successfully obtained for Pokemon with ID 128.
Data successfully obtained for Pokemon with ID 129.
Data successfully obtained for Pokemon with ID 129.
Data successfully obtained for Pokemon with ID 130.
Data successfully obtained for Pokemon with ID 130.
Data successfully obtained for Pokemon with ID 131.
Data successfully obtained for Pokemon with ID 131.
Data successfully obtained for Pokemon with ID 132.
Data successfully obtained for Pokemon with ID 132.
Data successfully obtained for Pokemon with ID 133.
Data successfully obtained for Pokemon with ID 133.
Data successfully obtained for Pokemon with ID 134.
Data successfully obtained for Pokemon with ID 134.
Data successfully obtained for Pokemon with ID 135.
Data successfully obtained for Pokemon with ID 135.
Data successfully obtained for Pokemon with ID 136.
Data successfully obtained for Pokemon with ID 136.
Data successfully obtained for Pokemon with ID 137.
Data successfully obtained for Pokemon with ID 137.
Data successfully obtained for Pokemon with ID 138.
Data successfully obtained for Pokemon with ID 138.
Data successfully obtained for Pokemon with ID 139.
Data successfully obtained for Pokemon with ID 139.
Data successfully obtained for Pokemon with ID 140.
Data successfully obtained for Pokemon with ID 140.
Data successfully obtained for Pokemon with ID 141.
Data successfully obtained for Pokemon with ID 141.
Data successfully obtained for Pokemon with ID 142.
Data successfully obtained for Pokemon with ID 142.
Data successfully obtained for Pokemon with ID 143.
Data successfully obtained for Pokemon with ID 143.
Data successfully obtained for Pokemon with ID 144.
Data successfully obtained for Pokemon with ID 144.
Data successfully obtained for Pokemon with ID 145.
Data successfully obtained for Pokemon with ID 145.
Data successfully obtained for Pokemon with ID 146.
Data successfully obtained for Pokemon with ID 146.
Data successfully obtained for Pokemon with ID 147.
Data successfully obtained for Pokemon with ID 147.
Data successfully obtained for Pokemon with ID 148.
Data successfully obtained for Pokemon with ID 148.
Data successfully obtained for Pokemon with ID 149.
Data successfully obtained for Pokemon with ID 149.
Data successfully obtained for Pokemon with ID 150.
Data successfully obtained for Pokemon with ID 150.
Data successfully obtained for Pokemon with ID 151.
Data successfully obtained for Pokemon with ID 151.

0      None
1      None
2      None
3      None
4      None
       ...
146    None
147    None
148    None
149    None
150    None
Name: pokemon_id, Length: 151, dtype: object